// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZyWBPzyiojjU20R70H72zPSOvtYzjSc',
    appId: '1:633796968326:web:a994feb8f27cd029cc7607',
    messagingSenderId: '633796968326',
    projectId: 'chat-app-319',
    authDomain: 'chat-app-319.firebaseapp.com',
    storageBucket: 'chat-app-319.appspot.com',
    measurementId: 'G-ECXBY4BP59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Yjn3vEV2Oq9fvtAm_oyxkMR-YKAZwms',
    appId: '1:633796968326:android:e138dfd8c66511d6cc7607',
    messagingSenderId: '633796968326',
    projectId: 'chat-app-319',
    storageBucket: 'chat-app-319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsx3klX65D--bOlnRN7dpw82sNewQtGtk',
    appId: '1:633796968326:ios:0d857d684b9a4ac9cc7607',
    messagingSenderId: '633796968326',
    projectId: 'chat-app-319',
    storageBucket: 'chat-app-319.appspot.com',
    iosClientId: '633796968326-4grnsttf3fkd2688p9l3efo90mhqiq25.apps.googleusercontent.com',
    iosBundleId: 'com.chat.soldier.chatApp',
  );
}
